add curl

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -52,11 +52,13 @@ jobs:
           fi
       - name: show env
         run: |
-          echo ${{ outputs.output1 }}
-      - name: Try to fail
-        if: ${{ outputs.output1 }} == "200"
-        run: |
-          exit 1
+          export FOO=bar
+          echo "::set-env name=FOO::$FOO"
+      - run: echo $FOO
+#      - name: Try to fail
+#        if: ${{ outputs.output1 }} == "200"
+#        run: |
+#          exit 1
 #      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
 #      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
 #      - name: Check out repository code
